ktor:
  application:
    modules:
      - ua.ihor0k.budgeter.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: postgres
  password: budgeter